import assert from "node:assert/strict";
await import("./pricing.js");
const P = globalThis.BBKPricing;
const byName = name => P.services.find(item => item.name === name);
assert.deepEqual(P.calculate(byName("BBK Basic Glam"), [], { enabled:false }), { base:75, addOns:0, total:75, deposit:25, balance:50, consultation:false, promotional:false });
assert.equal(P.calculate(byName("Silk Press"), [], { enabled:false }).total, 75);
assert.equal(P.calculate(byName("Silk Press"), P.addOns.filter(a => ["Shampoo","Trim"].includes(a.name)), { enabled:false }).total, 105);
assert.match(P.formatPrice(byName("Mini Braids")), /Starting at \$180/);
assert.match(P.formatPrice(byName("BBK Full Bridal Glam — Hair + Makeup for Bride + 3"), value => `$${value.toLocaleString("en-US")}`), /Starting at \$1,195/);
assert.equal(P.calculate(byName("BBK Full Bridal Glam — Hair + Makeup for Bride + 3"), [], { enabled:false }).deposit, 50);
assert.equal(P.calculate(byName("BBK Full Glam"), [], { enabled:false }).total, 150);
assert.match(P.formatPrice(byName("BBK Glam")), /\$250–\$300/);
assert.equal(byName("BBK Glam").questionnaire, "makeupParty");
assert.equal(P.depositFor(99.99), 25); assert.equal(P.depositFor(100), 40); assert.equal(P.depositFor(179.99), 40); assert.equal(P.depositFor(180), 50);
const promotion={enabled:true,startDate:"2026-01-01",endDate:"2026-12-31",prices:{"svc-silk-press":65}};
assert.equal(P.calculate(byName("Silk Press"), [], promotion, new Date("2026-07-26T12:00:00Z")).base,65);
assert.equal(P.promotionIsActive({...promotion,enabled:false},new Date("2026-07-26T12:00:00Z")),false);
assert.equal(P.promotionIsActive(promotion,new Date("2027-01-01T12:00:00Z")),false);
console.log("pricing tests passed");
assert.deepEqual(P.services.reduce((a,s)=>(a[s.category]=(a[s.category]||0)+1,a),{}), { Hair:8, Braids:3, Color:2, Weaves:7, Nails:7, Makeup:4 });
assert.equal(P.addOns.length, 10);
assert.equal(P.services.filter(s => s.category === "Color").every(s => s.requiredUploads.includes("current") && s.requiredUploads.includes("inspiration")), true);
assert.equal(P.services.filter(s => s.questionnaire === "pressOn").every(s => s.requiredUploads.includes("inspiration")), true);
console.log("catalog and conditional upload tests passed");
